version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: HTDB
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin_container
    restart: unless-stopped  # Restart phpMyAdmin container automatically
    environment:
      PMA_HOST: mysql  # Link to the mysql service
      PMA_USER: root  # Database username (set in mysql service)
      PMA_PASSWORD:
    ports:
      - "8081:80"  # Map phpMyAdmin port to your desired host port (e.g., 8080)
    depends_on:
      - mysql  # Ensure mysql service starts before phpMyAdmin

volumes:
  mysql_data: